### ISSUE TITLE
Sys.setCwd(_settingsDirectory) causes exception

### ISSUE THREAD

**Issue by cambiata** [Randonee/BasisAndroid#1]
Hi Randonee! Great to see this project!
When trying to compile, I get the following exeption though:

Called from basis/BuildTool.hx line 38
Called from Sys.hx line 91
Uncaught exception - std@set_cwd

I'm using a standard Haxe 2.10 setup on Windows 7.
Any clue?

**Comment by Randonee** [comment]
Hi,
Thanks for reporting this and sorry for the late reply. I'm still new to github and didn't see this issue.
There was a problem with how paths were handled on windows. This has been fixed and I've updated the haxelib to 0.0.2 so it can be easily installed and tested.
If your compiling the example you will need to get the 0.0.2 example here:
https://github.com/Randonee/BasisAndroid/tree/v0.0.2/example
Note: an extra argument (the target) is now needed when running the build command.
Example: haxelib run basis build.xml android

**Comment by cambiata** [comment]
Thank you! After setting the envronment var ANDROID_SDK to my android sdk path, compiling works, and so does the resulting null-debug.apk. Very interesting, indeed!

**Comment by Randonee** [comment]
The null in "null-debug.apk" sounds like another bug (it should be the name of the project). I'll take a look.
I'm working full time on ios in BasisApple right now. 
BasisAndroid is very limited currently. When haxe 3 comes out with all the new java improvements I'll work more on android. Hopefully a haxe 3  RC will be ready in a month or two.

**Comment by cambiata** [comment]
It's a good start, anyway! Looking forward to the next steps!
