### ISSUE TITLE
Could not build BasisAndroid ..

### ISSUE THREAD

**Issue by hopewise** [Randonee/BasisAndroid#2]
Hi, I tried to build BasisAndroid like this:

C:\Users\KETAB\Desktop\BasisAndroid-0.0.2\example>haxelib run Basis build.xml an
droid

I got:

Buildfile: C:\Users\KETAB\Desktop\BasisAndroid-0.0.2\example\build\android\build
.xml
BUILD FAILED
C:\Users\KETAB\Desktop\BasisAndroid-0.0.2\example\build\android\build.xml:25: Ca
nnot find C:\Users\KETAB\Desktop\BasisAndroid-0.0.2\example\build\android\${env.
ANDROID_SDK}\tools\ant\build.xml imported from C:\Users\KETAB\Desktop\BasisAndro
id-0.0.2\example\build\android\build.xml

Total time: 0 seconds
Called from ? line 1
Called from basisandroid/Main.hx line 7
Called from basis/BuildTool.hx line 50
Called from basis/settings/XmlSettings.hx line 32
Called from basis/BuildTool.hx line 64
Called from basisandroid/AndroidBuildTool.hx line 151
Called from basis/ProcessUtil.hx line 26
Uncaught exception - Error running: ant debug [build/android]

Any idea please?

**Comment by Randonee** [comment]
Looks like you need add ANDROID_SDK to your java class path. Make sure you can create/compile a simple app with the android sdk from the command line (without using haxe or Basis).

**Comment by hopewise** [comment]
ops, I found that ANDROID_SDK was not defined as an environment variable, although android sdk path is added to the paths variable ..

Any way, it works now, I can start experiments! thanks ..
